language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - composer install
  - vendor/bin/doctrine orm:schema-tool:create
  - mkdir -p build/logs

cache:
  directories:
    - vendor

after_success:
  - travis_retry php vendor/bin/coveralls -v
